# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-FormFactory
version:      0.58
version_from: lib/Gtk2/Ex/FormFactory.pm
installdirs:  site
requires:
    Gtk2:                          0
    Gtk2::SimpleList:              0
    Gtk2::SimpleMenu:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
